# NUNCA DEFINA VALORES ABERTOS/PUBLICOS/VISÍVEL AQUI!
# Sempre utilize os marcadores de substituição $(NOME-DA-SECRET-LIBRARY-AZURE-DEVOPS).
# Valores aberto devem ser definidos no arquivo environments_variables.yaml conforme o ambiente na pasta .azuredevops/helm
secrets:
  - name: DATABASE_HOST
    value: "$(DATABASE_HOST_DEV)"
  - name: DATABASE_PORT
    value: "$(DATABASE_PORT_DEV)"
  - name: DATABASE_NAME
    value: "$(DATABASE_NAME_DEV)"
  - name: DATABASE_USERNAME
    value: "$(DATABASE_USERNAME_DEV)"
  - name: DATABASE_PASSWORD
    value: "$(DATABASE_PASSWORD_DEV)"
  - name: REDIS_HOST
    value: "$(REDIS_HOST_DEV)"
  - name: REDIS_PORT
    value: "$(REDIS_PORT_DEV)"
  - name: REDIS_PASSWORD
    value: "$(REDIS_PASSWORD_DEV)"
  - name: SYNC_CONSENT_STATUS_TTL_REDIS
    value: "$(SYNC_CONSENT_STATUS_TTL_REDIS_DEV)"
  - name: CONSENT_IDEMPOTENCY_CHECK_TTL_REDIS
    value: "$(CONSENT_IDEMPOTENCY_CHECK_TTL_REDIS_DEV)"

  - name: EVENTHUB_CONNECTION_STRING
    value: "$(EVENTHUB_CONNECTION_STRING_DEV)"
  - name: EVENTHUB_NAME
    value: "$(EVENTHUB_NAME_DEV)"

  - name: OTEL_EXPORTER_OTLP_ENABLED
    value: "$(OTEL_EXPORTER_OTLP_ENABLED_DEV)"
  - name: OTEL_EXPORTER_OTLP_METRICS_ENABLED
    value: "$(OTEL_EXPORTER_OTLP_METRICS_ENABLED_DEV)"
  - name: OTEL_TRACES_SAMPLER_PROBABILITY
    value: "$(OTEL_TRACES_SAMPLER_PROBABILITY_DEV)"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "$(OTEL_EXPORTER_OTLP_ENDPOINT_DEV)"
  - name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
    value: "$(OTEL_EXPORTER_OTLP_LOGS_ENDPOINT_DEV)"
  - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
    value: "$(OTEL_EXPORTER_OTLP_METRICS_ENDPOINT_DEV)"
  - name: OTEL_LOG_EVENTS_ENABLED
    value: "$(OTEL_LOG_EVENTS_ENABLED_DEV)"

  #DEBEZIUM
  - name: DB_USER_DEBEZIUM
    value: "$(DB_USER_DEBEZIUM_DEV)"
  - name: DB_PASSWORD_DEBEZIUM
    value: "$(DB_PASSWORD_DEBEZIUM_DEV)"
  - name: KAFKA_API_KEY_DEBEZIUM
    value: "$(KAFKA_API_KEY_DEBEZIUM_DEV)"
  - name: KAFKA_API_SECRET_DEBEZIUM
    value: "$(KAFKA_API_SECRET_DEBEZIUM_DEV)"
  - name: KAFKA_SCHEMA_REGISTRY_URL
    value: "$(KAFKA_SCHEMA_REGISTRY_URL_DEV)"
  - name: KAFKA_SCHEMA_REGISTRY_KEY
    value: "$(KAFKA_SCHEMA_REGISTRY_KEY_DEV)"
  - name: KAFKA_SCHEMA_REGISTRY_PASSWORD
    value: "$(KAFKA_SCHEMA_REGISTRY_PASSWORD_DEV)"

secretFiles: []
