# NUNCA DEFINA VALORES ABERTOS/PUBLICOS/VISÍVEL AQUI!
# Sempre utilize os marcadores de substituição $(NOME-DA-SECRET-LIBRARY-AZURE-DEVOPS).
# Valores aberto devem ser definidos no arquivo environments_variables.yaml conforme o ambiente na pasta .azuredevops/helm 
secrets: 

- name: BMS_DATABASE_URL
  value: "$(BMS_DATABASE_URL_DEV)"
- name: BMS_DATABASE_USERNAME
  value: "$(BMS_DATABASE_USERNAME_DEV)"
- name: BMS_DATABASE_PASSWORD
  value: "$(BMS_DATABASE_PASSWORD_DEV)"

secretFiles: []
