# NUNCA DEFINA VALORES SECRETOS AQUI. Utilize o secrets.yml na raiz do .azuredevops
env:
- name: SPRING_PROFILES_ACTIVE
  value: prod
- name: JAVA_OPTS_METASPACE_MIN
  value: 128m
- name: JAVA_OPTS_METASPACE_MAX
  value: 384m

- name: REDIS_SSL
  value: "true"
- name: REDIS_TIMEOUT
  value: "10000"
- name: REDIS_CONNECT_TIMEOUT
  value: "5000"