# NUNCA DEFINA VALORES ABERTOS/PUBLICOS/VISÍVEL AQUI!
# Sempre utilize os marcadores de substituição $(NOME-DA-SECRET-LIBRARY-AZURE-DEVOPS).
# Valores aberto devem ser definidos no arquivo environments_variables.yaml conforme o ambiente na pasta .azuredevops/helm 
secrets: 
- name: DATABASE_URL
  value: "$(DATABASE_URL_PROD)"
- name: DATABASE_USERNAME
  value: "$(DATABASE_USERNAME_PROD)"
- name: DATABASE_PASSWORD
  value: "$(DATABASE_PASSWORD_PROD)"
- name: REDIS_HOST
  value: "$(REDIS_HOST_PROD)"
- name: REDIS_PORT
  value: "$(REDIS_PORT_PROD)"

- name: EVENTHUB_CONNECTION_STRING
  value: "$(EVENTHUB_CONNECTION_STRING_PROD)"
- name: EVENTHUB_NAME
  value: "$(EVENTHUB_NAME_PROD)"

- name: OTEL_EXPORTER_OTLP_ENABLED
  value: "$(OTEL_EXPORTER_OTLP_ENABLED_PROD)"
- name: OTEL_EXPORTER_OTLP_METRICS_ENABLED
  value: "$(OTEL_EXPORTER_OTLP_METRICS_ENABLED_PROD)"
- name: OTEL_TRACES_SAMPLER_PROBABILITY
  value: "$(OTEL_TRACES_SAMPLER_PROBABILITY_PROD)"
- name: OTEL_EXPORTER_OTLP_ENDPOINT
  value: "$(OTEL_EXPORTER_OTLP_ENDPOINT_PROD)"
- name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
  value: "$(OTEL_EXPORTER_OTLP_LOGS_ENDPOINT_PROD)"
- name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
  value: "$(OTEL_EXPORTER_OTLP_METRICS_ENDPOINT_PROD)"

secretFiles: []
