FROM vcr-docker.nexus.telefonica.com.br/base/code/java/21/runtime:1.0.2

ARG APPLICATION_NAME
ENV APPLICATION_NAME=$APPLICATION_NAME
ENV JAR_NAME="$APPLICATION_NAME.jar"

ARG APPLICATION_PATH
ENV APPLICATION_PATH=$APPLICATION_PATH

ADD $APPLICATION_PATH/$JAR_NAME $JAR_NAME

VOLUME /config

ENV JAVA_MEMORY_RAM_MIN_PERCENTAGE="40.0"
ENV JAVA_MEMORY_RAM_MAX_PERCENTAGE="90.0"
ENV JAVA_OPTS_METASPACE_MIN="64m"
ENV JAVA_OPTS_METASPACE_MAX="128m"

ENV JAVA_OPTS_MEMORY="-XX:MinRAMPercentage=$JAVA_MEMORY_RAM_MIN_PERCENTAGE -XX:MaxRAMPercentage=$JAVA_MEMORY_RAM_MAX_PERCENTAGE -XX:MetaspaceSize=$JAVA_OPTS_METASPACE_MIN -XX:MaxMetaspaceSize=$JAVA_OPTS_METASPACE_MAX"
ENV JAVA_OPTS="$JAVA_OPTS_MEMORY $JAVA_OPTS_CONFIG -Djava.security.egd=file:/dev/./urandom"

EXPOSE 8082
ENTRYPOINT java $JAVA_OPTS -jar $JAR_NAME