# NUNCA DEFINA VALORES SECRETOS AQUI. Utilize o secrets.yml na raiz do .azuredevops
env:
- name: SPRING_PROFILES_ACTIVE
  value: hml
- name: JAVA_OPTS_METASPACE_MIN
  value: 128m
- name: JAVA_OPTS_METASPACE_MAX
  value: 384m
