# NUNCA DEFINA VALORES ABERTOS/PUBLICOS/VISÍVEL AQUI!
# Sempre utilize os marcadores de substituição $(NOME-DA-SECRET-LIBRARY-AZURE-DEVOPS).
# Valores aberto devem ser definidos no arquivo environments_variables.yaml conforme o ambiente na pasta .azuredevops/helm
secrets:
- name: DATABASE_HOST
  value: "$(DATABASE_HOST_HML)"
- name: DATABASE_PORT
  value: "$(DATABASE_PORT_HML)"
- name: DATABASE_NAME
  value: "$(DATABASE_NAME_HML)"
- name: DATABASE_USERNAME
  value: "$(DATABASE_USERNAME_HML)"
- name: DATABASE_PASSWORD
  value: "$(DATABASE_PASSWORD_HML)"
- name: REDIS_HOST
  value: "$(REDIS_HOST_HML)"
- name: REDIS_PORT
  value: "$(REDIS_PORT_HML)"
- name: REDIS_PASSWORD
  value: "$(REDIS_PASSWORD_HML)"
- name: SYNC_CONSENT_STATUS_TTL_REDIS
  value: "$(SYNC_CONSENT_STATUS_TTL_REDIS_HML)"
- name: CONSENT_IDEMPOTENCY_CHECK_TTL_REDIS
  value: "$(CONSENT_IDEMPOTENCY_CHECK_TTL_REDIS_HML)"

- name: EVENTHUB_CONNECTION_STRING
  value: "$(EVENTHUB_CONNECTION_STRING_HML)"
- name: EVENTHUB_NAME
  value: "$(EVENTHUB_NAME_HML)"

- name: OTEL_EXPORTER_OTLP_ENABLED
  value: "$(OTEL_EXPORTER_OTLP_ENABLED_HML)"
- name: OTEL_EXPORTER_OTLP_METRICS_ENABLED
  value: "$(OTEL_EXPORTER_OTLP_METRICS_ENABLED_HML)"
- name: OTEL_TRACES_SAMPLER_PROBABILITY
  value: "$(OTEL_TRACES_SAMPLER_PROBABILITY_HML)"
- name: OTEL_EXPORTER_OTLP_ENDPOINT
  value: "$(OTEL_EXPORTER_OTLP_ENDPOINT_HML)"
- name: OTEL_EXPORTER_OTLP_LOGS_ENDPOINT
  value: "$(OTEL_EXPORTER_OTLP_LOGS_ENDPOINT_HML)"
- name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
  value: "$(OTEL_EXPORTER_OTLP_METRICS_ENDPOINT_HML)"
- name: OTEL_LOG_EVENTS_ENABLED
  value: "$(OTEL_LOG_EVENTS_ENABLED_HML)"

#DEBEZIUM
- name: DB_USER_DEBEZIUM
  value: "$(DB_USER_DEBEZIUM_HML)"
- name: DB_PASSWORD_DEBEZIUM
  value: "$(DB_PASSWORD_DEBEZIUM_HML)"
- name: KAFKA_API_KEY_DEBEZIUM
  value: "$(KAFKA_API_KEY_DEBEZIUM_HML)"
- name: KAFKA_API_SECRET_DEBEZIUM
  value: "$(KAFKA_API_SECRET_DEBEZIUM_HML)"
- name: KAFKA_SCHEMA_REGISTRY_URL
  value: "$(KAFKA_SCHEMA_REGISTRY_URL_HML)"
- name: KAFKA_SCHEMA_REGISTRY_KEY
  value: "$(KAFKA_SCHEMA_REGISTRY_KEY_HML)"
- name: KAFKA_SCHEMA_REGISTRY_PASSWORD
  value: "$(KAFKA_SCHEMA_REGISTRY_PASSWORD_HML)"

secretFiles: []
